### PR TITLE
Feature manager and host

### PR DESCRIPTION
**Pull request by TakayukiHoshi1984**

### CODE REVIEW

**Comment by Onuzimoyr** [comment]
Please revise link addresses and descriptions from "Takayukihoshi1984" to "DeviceConnect" in readme.me in order for users to access and refer correct position.

Besides I need to make sure whether command is same or not in command operating "install" and "run".
(When I followed the instruction in readme.md, https://github.com/TakayukiHoshi1984/DeviceConnect-NodeJS/blob/feature_manager_and_host/packages/deviceconnect-manager/README.md, Node.js command prompt gave me an error when trying to do "npm start".

**Comment by masaru-takano** [comment]
> Please revise link addresses and descriptions from "Takayukihoshi1984" to "DeviceConnect" in readme.me in order for users to access and refer correct position.

We modified link addresses in Readme. Please confirm the commit below: https://github.com/DeviceConnect/DeviceConnect-NodeJS/pull/1/commits/b530622cdbfbab176c5e4159a9af5ad7d0b2b1cb

> Besides I need to make sure whether command is same or not in command operating "install" and "run".
> (When I followed the instruction in readme.md, https://github.com/TakayukiHoshi1984/DeviceConnect-NodeJS/blob/feature_manager_and_host/packages/deviceconnect-manager/README.md, Node.js command prompt gave me an error when trying to do "npm start".

Sorry for inconvenience. We modified the "Run" section in Readme of Device Connect Manager and Host.
In addition, Wiki also has been modified so that all procedure for preparation are visible.
Would you refer below Wiki to try again?

https://github.com/TakayukiHoshi1984/DeviceConnect-NodeJS/wiki

**Comment by Onuzimoyr** [comment]
Thank you for your reply on this.

> We modified the "Run" section in Readme of Device Connect Manager and Host.

Please check directory path in readme.md
(https://github.com/TakayukiHoshi1984/DeviceConnect-NodeJS/blob/feature_manager_and_host/packages/deviceconnect-manager/README.md)

I think it should not be "package" but "packages"
$ cd DeviceConnect-NodeJS/package/deviceconnect-manager
$ npm start

If done in host side as well, please do same check.
Besides after followed new readme's instruction, npm returns below error.

If anything wrong I made, please kindly let me know.

For wiki, it seems to need raspberry pi beforehand, but anyway will upload to DeviceConnect.
++++++++++++++++++++++++++++++++
module.js:341
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Projects\GitHub\GClue\DeviceConnect-NodeJS\packages\deviceconnect-manager\deviceconnect-ma
nager.js:1:77)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! deviceconnect-manager@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deviceconnect-manager@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the deviceconnect-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs deviceconnect-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls deviceconnect-manager
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\GitHub\GClue\DeviceConnect-NodeJS\packages\deviceconnect-manager\npm-debug.log

**Comment by masaru-takano** [comment]
> I think it should not be "package" but "packages"
> $ cd DeviceConnect-NodeJS/package/deviceconnect-manager
> $ npm start
> 
> If done in host side as well, please do same check.

Sorry, the path for installation of deviceconnect-manager was wrong.
You need to execute `npm install` on the following directory.

```
$ cd DeviceConnect-NodeJS/packages/deviceconnect-manager/
$ npm install
```

By the above command, the module 'express' is installed and the reported error will not be appeared.

Please check the below commit: https://github.com/DeviceConnect/DeviceConnect-NodeJS/pull/1/commits/1900e388fad468b738668d62700b794400e6464b

**Comment by masaru-takano** [comment]
**Further Note:**

Please use Raspberry Pi 2 Model B and below environments when you try the branch 'feature_manager_and_host' in whole.

https://github.com/TakayukiHoshi1984/DeviceConnect-NodeJS/wiki#section2

In other environments, the all APIs of the host device plug-in will be unavailable, or the build for audio add-on described in the below section will be failed.

https://github.com/TakayukiHoshi1984/DeviceConnect-NodeJS/wiki#section3-7

**Pull request merged**
